### PR TITLE
extensions Hashcode

### PR DESCRIPTION
**Pull request by moh-sushi**
Hi,

PR consists of
- new methods without seed - value 
  - give the user the choice if user wants to use its own seed value of use the internal one
    - wdyt?
- tests added for `jodd.util.HashCodeTest`

Bye,
Sascha

### CODE REVIEW

**Comment by igr** [comment]
Heya! Thanx for the PR:) I think we can't simply allow the user to use back the original `SEED`. You see, the usage is the following:

```java
int result = HashCodeUtil.SEED;
result = HashCodeUtil.hash(result, value1);
result = HashCodeUtil.hash(result, value2);
....
return result;
```

So `SEED` is only the starting seed, and, afaik, we should not change the seed during the calculation; otherwise, there would be no correlation between the fields.

But I don understand your intent - and I guess the way to solve is to make `HashCode` not with static methods, but:

```java
     HashCode.create()
          .hash(value1)
          .hash(value2)
          .get();
````

and in case of custom seed and prime: `HashCode.create(seed, prime)...`

where the calculated result is simply updated.

**Comment by igr** [comment]
However, my idea would create a new class on each hashcode call.
Now I remember that I wanted to avoid that, because of performances.

**Comment by moh-sushi** [comment]
> So SEED is only the starting seed, and, afaik, we should not change the seed during the calculation; otherwise, there would be no correlation between the fields.

I admit my mistake - damn it...

```
HashCode.create(seed,prime) // seed & prime optional
          .hash(value1)
          .hash(value2)
          .get();
```
I like the API proposal.


> However, my idea would create a new class on each hashcode call.
> Now I remember that I wanted to avoid that, because of performances.

Is the creation of the hashcode class so critical for performance? ...

A benchmark should help us, right?! ;-)

**Comment by igr** [comment]
Yap, adding benchmark as we speak :) Last night i just collapsed.

**Comment by igr** [comment]
```
HashCodeBenchmark.hashCode_noInstance    thrpt   10  418009852.674 ±  8233326.541  ops/s
HashCodeBenchmark.hashCode_withInstance  thrpt   10  413934971.659 ± 15330555.186  ops/s
```

nice!

**Pull request closed without merging**
