### PR TITLE
small enhancement PathUtil and tests added for PathUtilTest

### PR DESCRIPTION
**Pull request by moh-sushi**
Hi,

PR constsis of:
- small enhancement of `jodd.io.PathUtil`
  - usage of try-with-resources
- tests added for `jodd.io.PathUtilTest`
- move class `jodd.io.PathUtilTest` into correct package (old : `jodd.util.PathUtilTest`)

bye,
Sascha

### CODE REVIEW

**Comment by zqq90** [comment]
@moh-sushi 
well done!
But one little tip: the indent should be `\t`, even though I prefer four-space too.

**Comment by moh-sushi** [comment]
> well done!

Thank you, @zqq90 !

> But one little tip: the indent should be \t, even though I prefer four-space too.

I have converted spaces to tabs. Thank for your hint, @zqq90 !

**Comment by igr** [comment]
Thank you @moh-sushi! I've added a comment regarding the lock, it is all fine.

**Comment by moh-sushi** [comment]
> I've added a comment regarding the lock, it is all fine.

Okay - i have read your comment :-)

**Pull request merged**
