### PR TITLE
Update STYLEGUIDE.md

### PR DESCRIPTION
**Pull request by moh-sushi**
added public modifier for nested test methods

### CODE REVIEW

**Comment by igr** [comment]
I wonder if having public methods makes sense on protected class. Maybe nested class should be public too? wdyt?

**Comment by igr** [comment]
Maybe we can simplify and have everything `public`?

**Comment by igr** [comment]
btw, I can change the code, just let's agree on the style :)

**Comment by moh-sushi** [comment]
Well, this problem is based on the new junit 5 - features.
You do not need `public` modifier on test method as well as class anymore.

idea1 : 
- usage `public `modifier on **all** test methods & test classes
   - includes nested classes and methods in nested classes

idea 2:
- usage of package private on **all** test methods & test classes
  - no exclusions

idea 3:
- mix of idea 1 & 2
- up to the author of the tests

Well, i like the new feature of junit 5 (no requirement of public on class and method) and therefore i would vote idea 2. But this a break of present tests and many many tests has to be refactored.
but i can live with idea 1. and with idea 1 is only few tests must be refactored :-)

idea 3 is a no-go - coding styles should be equal in all places.

**Comment by igr** [comment]
I agree it's either 1 or 2, to preserve the unique style across the library.

I see that Junit5 really writes package scoped classes everywhere, which totally makes sense. Let me see how big impact this change would have on the library,

**Comment by moh-sushi** [comment]
> Let me see how big impact this change would have on the library,

Well, it does matter what do you want:
Iterate over all test classes and substitute public modifier with package private for class itself and test methods.
You can create several issues for every jodd-module.
I can help - of course.
I was thinking of a manual process.

Or are you thinking of semi-automated processes using groovy?

**Comment by igr** [comment]
I have updated the tests and the style guide... sorry for not merging, just have quickly changed the MD.

**Comment by moh-sushi** [comment]
> I have updated the tests and the style guide

:+1: 

> sorry for not merging, I just quickly changed the MD.

No Problem!

**Pull request closed without merging**
