### PR TITLE
Implement modifyHeaderKeys option

### PR DESCRIPTION
**Pull request by brandon8863**
#424

### CODE REVIEW

**Comment by neroux** [comment]
:+1:

Only one remark, maybe a better wording than just _modify_. Maybe `capitaliseHeaderNames`? Or something with camel/Pascal case ....

**Comment by neroux** [comment]
Just to clarify, wouldnt these need a check for `capitaliseHeaderKeys` as well?
- [header()](https://github.com/brandon8863/jodd/blob/d18c52be136b09ae8174837c837d88ccfebab9ea/jodd-http/src/main/java/jodd/http/HttpBase.java#L122)
- [removeHeader()](https://github.com/brandon8863/jodd/blob/d18c52be136b09ae8174837c837d88ccfebab9ea/jodd-http/src/main/java/jodd/http/HttpBase.java#L136)
- [_header()](https://github.com/brandon8863/jodd/blob/d18c52be136b09ae8174837c837d88ccfebab9ea/jodd-http/src/main/java/jodd/http/HttpBase.java#L180)

**Comment by igr** [comment]
Yeah, let me add more test cases for this.

**Comment by brandon8863** [comment]
Good question. I started by looking at the HttpMultiMapTest which looks like case won't matter since it's backed by a case insensitive map. Tests would verify though.

**Comment by neroux** [comment]
> Good question. I started by looking at the HttpMultiMapTest which looks like case won't matter since it's backed by a case insensitive map. Tests would verify though.

A very good point, which I seem to have missed, respectively mixed up. I sent you a PR where I removed all the lowercasing :)

**Comment by igr** [comment]
Thank you guys for this PR!

@neroux nice catch with the removal of unnecessary `toLowercase()`!

I found one issue with this. Lets say we have this:

```
request = HttpRequest.get("")
			.capitaliseHeaderKeys(false)
			.header("KEY-TEST1", "VALUE1");
```

If, for some reason, we add the same header again, but with different capitalization:
```
request.header("key-test1", "value1-1");
```
what would you expect to happen? My first guess was to expect 2 headers:

+ KEY-TEST1:VALUE1
+ key-test1:value1-1

However, this is not happening; instead we have:

+ KEY-TEST1:VALUE1
+ KEY-TEST1:value1-1

which means that with duplicated names, the used header will be set by the first `header()` call.

For that reason, I have added some code after yours - basically, introducing the Tuple for header key/values. Would you be so kind to check if that makes sense?

One more thing about the wording - I feel that now this is not only capitalization behavior that is all about, since of this behavior with the double headers. How about to change it to `useStrictHeaderNames` or something similar? Just because this flag now turns more than just capitalization. WDYT?

**Comment by brandon8863** [comment]
@igr Nice catch and I agree on the name change now that it affects more than capitalization.

**Comment by neroux** [comment]
> what would you expect to happen? My first guess was to expect 2 headers:

@igr I'd agree with the expectations, though I think there is something else off. In your example the second header should have never been rewritten, and yet it was. I'll have a quick look at it and get back to you as soon as possible :)

**Comment by igr** [comment]
Sure @neroux please check my latest commit. The logic is not changed, and now the second header is not rewritten :)

Anyway, take your time, no hurry. See if there is something we might be missing.

**Comment by neroux** [comment]
Quick feedback, it seems that HttpMultiMap merged the two headers into one (more precisely, `HttpMultiMap.names()` merges them into one via the case insensitive TreeSet) for determining the names but then still returned two values for that name, as two values were added.

I quickly checked out the [appropriate section of the HTTP RFC](https://tools.ietf.org/html/rfc7230#section-3.2.2)
> A sender MUST NOT generate multiple header fields with the same field name in a message unless either the entire field value for that header field is defined as a comma-separated list [i.e., #(values)] or the header field is a well-known exception (as noted below).

So I guess more than one header with the same name (regardless of case) should never be returned, unless it is flattened into a comma-separated form or one of the - surprise :) - exceptions.

As for the tuple class, to be honest I havent understood yet how that should make things different from the earlier implementation.

**Comment by igr** [comment]
Ok, to make resume now. There are two things to consider here:

1. header keys capitalization;
2. header keys duplication.

+ in **non-strict** mode (default one), `HttpRequest` works as in RFC. Meaning, 1) no matter how you specify, the header key will be rewritten and different capitalizations mean the same key, and 2) duplicate header keys, therefore, does not exist.

+ In **strict mode**, `HttpRequest` does not follow the RFC. 1) If we specify same header keys but with different capitalization, they will be treated semi-differently: when writing headers, they will be written as they were specified, but for all other methods capitalization is ignored; and 2) header would be duplicated if same name but different capitalization.

While I agree on having the **strict** mode where the input would be exactly as the header was specified, I wonder what should happen in *strict* mode when user does this:

    request.header("FOO", "value1");
    request.header("foo", "value2");

By the RFC this is the same, and in **non-strict** mode the headers would be merged into one header key with two values.

But what would happen in **strict** mode?

Maybe, in that case, we can simply _rewrite_ the key!!! So the result would be always the last header.

WDYT @neroux ?

**Comment by igr** [comment]
Hey @neroux and @brandon8863 , finally made it: https://github.com/oblac/jodd/commit/26b14f773d1ebe826d321b133b4dca0d3aada506

Sorry for this long trip around this issue. Now it behaves sanely.

@neroux thanx for pointing out the RFC, I actually fixed the bug with multiple values!!!

The behaviour:

### default mode (non-strict) == RFC

1) different capitalisation means no difference. Header keys will be outputed using PascalCase
2) setting different values to the same name will just add values to the same key, regardless the capitalisation

### strict mode 

1) different capitalisation makes no difference. However! Keys are outputed using the LAST header definition
2) same as above.

Hence:

    .header("FOO", "value1").header("foo", "value2")

would give:

    foo: value1, value2

And it's `foo` because it is the LAST name used.

**Comment by neroux** [comment]
Havent had an in-depth look yet, but sounds good from your description :). I'll look at it more in detail later today and will get back to you.

**Comment by neroux** [comment]
@igr Apologies for the delayed response. Just gave it a quick test and it looks good. I'd rename the flag again however, as it is not about "strictness" anymore but only about as-is case or Pascal casing. It could be actually a bit misleading as the strict mode would be the most liberal.

**Comment by igr** [comment]
I agree @neroux, I am just about to rename it back :)

No worries, you are just in time (before the release;)

**Pull request merged**
