### PR TITLE
test class for JtxDbUtil added

### PR DESCRIPTION
**Pull request by moh-sushi**
Hi,

tests for class `jodd.db.jtx.JtxDbUtil `added.

Bye,
Sascha

### CODE REVIEW

**Comment by igr** [comment]
Hey @moh-sushi

**Comment by igr** [comment]
Very important.

**Comment by igr** [comment]
It is like super-important I need to share it with you

**Comment by igr** [comment]
So.

**Comment by igr** [comment]
image

## Thank you for reaching #501 PRs :)

**Comment by moh-sushi** [comment]
Hi @igr ,

many many many manyyyy thanks for this award :-)

I will keep in mind #501 PR for a very long time  :-)

**Pull request merged**
