### PR TITLE
Optimize empty String tests on Java 9+

### PR DESCRIPTION
**Pull request by slandelle**
Motivation:

Don't use String#length() to test emptyness. This computes the actual length, which might be non trivial with Java 9 where the underlying encoding is UTF-8 and not US-ASCII.
Use String#isEmpty() instead as it just has to check the length of the nuderlying byte array.

Modifications:

* string.length() == 0 => string.isEmpty()
* string.length() != 0 => !string.isEmpty()
* string.length() > 0 => !string.isEmpty()
* overload StringUtil#isEmpty to accept a String where implementation can be optimized. Original method doesn't seem to be used but it's public so I didn't remove it.

Result:

More performant String emptiness test

### CODE REVIEW

**Comment by slandelle** [comment]
Honestly, codecov is drunk...

**Comment by igr** [comment]
Crazy:) Thank you @slandelle!

I am finalizing the migration to v6 and separating/grouping repos atm, so your change will be applied to all new repos plus to whatever remains here.

**Comment by slandelle** [comment]
Ah OK. Please let me know if you want me to redo this PR on the different projects once the migration is done.

**Comment by igr** [comment]
No need, thank you! At this moment, just need to do all that by myself, until its finished and released; will be just easier.

**Comment by igr** [comment]
Fixed in jodd-util and jodd-lagarto

**Pull request closed without merging**
