### PR TITLE
Added CommandLine and CommandLineBuilder to easily execute native applications

### PR DESCRIPTION
**Pull request by vilmospapp**
Hi Igor,

I formerly promised to send this to you, but had busy weeks, could you please review it?

Regards,
Vilmos

### CODE REVIEW

**Comment by igorspasic** [comment]
Just started reviewing :)<br>:rocket:

**Comment by igorspasic** [comment]
Heya, no problem, thank you! One question: I see that `CommandLineBuilder` can be merged into `CommandLine`. Then everything would be in the same class...

wdyt?

**Comment by igorspasic** [comment]
Something like: fdec0fce2f30a677b6717bf754c353bd67d5c61b

**Comment by vilmospapp** [comment]
Seems good for me ;-)
-- 
Vilmos Papp
Engineer, Technical Support
Subscription Services | EMEA

Liferay Hungary | Madarász Viktor u. 47., 1138, Budapest, Hungary


On 5 Apr 2015 at 23:32:33, Igor Spasić (notifications@github.com) wrote:

Something like: fdec0fc

**Comment by igorspasic** [comment]
One question regarding Mac: shouldn't we be able to run the following:

    CommandLine.cmd("ls").execute();

This would work on *nix, but it is not working on Mac as it will call 'open'. Right?

**Comment by vilmospapp** [comment]
You're right, probably an extra check needed for Mac like: has no extension and file is binary if so, then sh -c should be used.

**Comment by vilmospapp** [comment]
Hi Igor,

I added some more fix, could you review this? I've pushed it over the original fix and applied your modifications on it as well.

**Comment by igorspasic** [comment]
Just started reviewing :)<br>:rocket:

**Pull request merged**
