### PR TITLE
Release uts 224

### PR DESCRIPTION
**Pull request by charuvijay**
Dear Team,

This pull request is focused on jodd-log module.
Code coverage is measured using JaCoCo. This pull request increases code 
coverage of the whole project by 96%.

Metric             | Before| After
------------------|----------|-------

Coverage%    |37%     |96%

Lines Covered|354      |918

Total Lines      |354     |918
   

Please let me know if you have any questions.

Vijay
DevFactory - Code Quality Team.

### CODE REVIEW

**Comment by igorspasic** [comment]
Just started reviewing :)<br>:rocket:

**Comment by igorspasic** [comment]
Awesome!!! Just uploaded the coverage here as well: https://coveralls.io/github/oblac/jodd

Just few notes:

+ don't need to squash commits, we are ok with many :)
+ i've just re-enabled the `testAll` for all modules, but didn't delete the `javaTestModules` - please keep using it so at the end we can use it in the `testAll` task, as you have planned!

:+1: :+1: :+1:  Thank you!

**Comment by igorspasic** [comment]
Also feel free to add reference to DevFactory  in the CODE_COVERAGE file, i think its fair :)

**Comment by mfarid** [comment]
Thanks a lot @igorspasic for your prompt action in reviewing our PR and accepting it. It gives us a lot of motivation and confidence of doing such contributions.

Thank again
Farid

**Comment by igorspasic** [comment]
Thank you @mfarid for the contribution!
I was so happy today seeing total code coverage goes up :)))

**Pull request merged**
