### PR TITLE
Deep copy

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by igorspasic** [comment]
Just started reviewing :)<br>:rocket:

**Comment by igorspasic** [comment]
I need to check this in more details :) First I would try to reuse `visitProperty` method from the base class, and so on.

Thanks, just stay tuned!

**Comment by marcellustavares** [comment]
Np, thx @igorspasic

**Comment by igorspasic** [comment]
Sorry for long reply! I needed some time to fully understand your needs ;)

So this is not exactly the deep copy, as values are not cloned; instead we perform the bean copy. And that is the main reason why we can not proceed with this: detection of the types that are beans is... tricky. You have put them in the list called `primitives`, and there you can find, besides the real primitives, types like `String` and `Locale`. But that is not enough. There are plenty of other Java types that are not beans: `Calendar`, `*Stream`, `*Reader`, `StringBuilder`, `TimeZone`, `BigDecimal`, `BigInteger` and so on and on. Not to mention 3rd party types. Also, need to cover `enums` etc. 

I don’t see a reasonable way to handle this? Maybe we can exclude all java.* types.

I was going in direction where you can specify for each target property one of the following:

+ to clone source to target (deep copy)
+ to copy source reference to target (shallow copy)
+ to create new instance with optionally specified type and perform bean copy

Also, there is one case not covered in your code, that is when source is eg. a `Map` and destination is a bean - and vice/versa.

I think such class would be quite complex and at the end not very fall this is not easy neither fast to implement this in generic-it-works-for-all way.

**Pull request closed without merging**
