### PR TITLE
add .after, .unwrap, .replaceWith-operations to jerry

### PR DESCRIPTION
**Pull request by cproof**
Jerry supports the .before()-operation, but no .after(). Since I love using jerry in one of my projects and don't want to apply a workaround, I added the .after()-operation to jerry.

### CODE REVIEW

**Comment by cproof** [comment]
Should I fix the codacity problem? Using a different variable name would be inconsitent with previous code.

**Comment by igorspasic** [comment]
Hey @cproof! Thanx for the PR! That is awesome!

Ignore codacy for the moment, we are still applying it - they have some bug, and I can't configure it until their bug is resolved.

**Comment by igorspasic** [comment]
Just started reviewing :)<br>:rocket:

**Comment by cproof** [comment]
Thanks! I just amended once more, forgot to commit the correct documentation

**Comment by igorspasic** [comment]
Great, just in time :)))

**Comment by cproof** [comment]
Thanks! :)

**Pull request merged**
