### PR TITLE
Correct javadoc,add IsValue, RandomString

### PR DESCRIPTION
**Pull request by wenerme**
RandomString allowed regenerate same random string.
IsValue is the immutable version of ValueHolder, Like Supplier in guava.
BTW, I think ValueHolder should be interface not class.

### CODE REVIEW

**Comment by igorspasic** [comment]
Nice! Two questions:

+ Maybe we can remove `RandomStringUtil` in favor of `RandomString`? I.e. not much need for delegates now?

+ Yeah, `ValueHolder` may be an interface. Where would you put initial implementation?

**Comment by wenerme** [comment]
* I think we can keep `RandomStringUtil` .just use the create method to initialize new `RandomString` instance.Like `Math.random`, use `RandomStringUtil` just want to get a random string, no more instance.

* Change `ValueHolder` to interface may break compatibility, put this to next major version ?
* Then here should be a `ValueUtil` factory class to help this.

**Comment by igorspasic** [comment]
Yeah, but `Math.random` only gives a random double, it's not a full delegate to all `Random` methods. So instead of `*Util` class, I've added a default constant; just don't like to repeat all the delegation:)

There would not be much compatibility breaks I am aware of ;) I am sorry, but at the moment we are not able to maintain the changes in a proper way, as you suggested - simply not much resources for that. So minor changes, like this one still, will be notified in the release notes...

**Comment by igorspasic** [comment]
Thank you for your submission, that is very valuable :+1:

**Comment by igorspasic** [comment]
Btw, `ValueHolder` is now interface ;)

**Pull request merged**
