### PR TITLE
Fix and optimize LazyMap

### PR DESCRIPTION
**Pull request by slandelle**
Motivation:

LazyMap was taken from Boon.

* There is some code that's not used in the scope of Jodd.
* `containsKey` and `containsValue` don't need to load the HashMap when there are just a few entries

Modification:

Contribute changes that have been used in Gatling for some time.

Result:

More efficient LazyMap implementation.

### CODE REVIEW

**Comment by slandelle** [comment]
@igr With #687 and this one, I'm done for now.

**Comment by igr** [comment]
Expect the release today :) Just to review, merge and solve another request, and its good to go!

**Comment by slandelle** [comment]
Thanks a lot!

**Comment by igr** [comment]
LGTM

Nice, nice!!!

**Pull request merged**
