### PR TITLE
extensions for PropsUtilTest

### PR DESCRIPTION
**Pull request by moh-sushi**
Hi,

PR consists of:

- change method modifier for all test methods to package-private
- tests for Method PropsUtil#createFromClasspath() added

Bye,
Sascha

### CODE REVIEW

**Comment by igr** [comment]
Awesome! GIve me a day or so, please, I already have part of this changes. Working on some bigger refactoring atm :)

**Comment by moh-sushi** [comment]
no problem :-)

**Comment by igr** [comment]
/_off topic_/ which static method name would you prefer in the code:

 + `defaults()`
 + `config()`

This method would return default settings for the module. I was trying to avoid 'config' as it is not a runtime configuration, but a default one, as all the configs can be set during the usage, anyway - hence, its defaults. wdyt?

**Comment by igr** [comment]
Thanx for this... These methods were submitted like that and I just never renamed to proper syntax.

**Pull request merged**
